### ISSUE TITLE
Rebuilding PROD container doesn't update settings.yml

### ISSUE THREAD

**Issue by j0nathanr** [US-Artificial-Intelligence/abbey#14] opened 2024-12-19 22:25 UTC
Per documentation, rebuilding the production container should reload settings.yml. However, after attempting to implement TTS and rebuilding the container, the settings didn't update.

```
docker compose down
docker compose -f docker-compose.prod.yml up --build

```
I tested this further by removing the auth integration from settings.yml and rebuilding the container, yet I'm still presented with OIDC login. Bringing the dev container back up to see if the changes are reflected doesn't seem to work either as I can't reach the web ui.

I've also confirmed the updated settings.yml is readable in the containers.

**Comment by gkamer8** [comment] 2024-12-19 23:26
Hi - just merged a fix from dev to fix. Has to do with the volume mounting after the build (see: change in the Dockerfile.prod). Let me know if that works!

**Comment by j0nathanr** [comment] 2024-12-19 23:59
Awesome, that fixed this issue. I confirmed by toggling the auth on and off. However, I can't tell if TTS has been enabled or not.
I assumed I'd see an option under the chat messages to speak aloud but nothing is there, is it implemented differently?

**Comment by gkamer8** [comment] 2024-12-20 00:02
Hi– I should definitely implement that specific case, I'll add to the list. You can tell that TTS is enabled if you see a speaker option in summaries (which will read the summary out loud) and an "Audio" option in the menu bar above documents (that will try to rewrite the document for audio and then read it to you).

**Comment by j0nathanr** [comment] 2024-12-20 00:20
Thanks, I do see the icon however when clicked it just seems to spin indefinitely. The TTS server doesn't show any incoming requests from Abbey either. Anyway to troubleshoot this? I don't see any logs in the frontend or backend, dev consoles throws a 404 error for the url below:

https://abbey.domain.domain/socket.io?EIO=4&transport=polling&t=PFXQaea

*note I'm running this behind an nginx reverse proxy if that possibly has anything to do with it.

**Comment by gkamer8** [comment] 2024-12-20 00:25
If there's a 404 there, and no logs on the backend (even in dev mode?) it seems like the abbey server (which would fire the TTS request) is itself never getting the request. Looking at that domain, it's "abbey.domain.domain" - that doesn't seem right? It should be your abbey backend URL. So first I would check your settings.yml to make sure that your URLs are all correct.

If that's not the issue, please send over your settings.yml and more details about your setup, like which API you're trying to use, which model, etc. Then I'll open a new issue for it. Thanks!

EDIT: wait you definitely meant "abbey.XXX.XXX" so that seems unlikely to be the issue. I'm just going to open up the new issue and investigate.

**Comment by j0nathanr** [comment] 2024-12-20 00:35
I can do some more testing on my side as I only tried this in production. Yep, domain.domain is just a placeholder for my personal domain, but the backend url should be abbey.xxx.xxx/backend, so perhaps something is a matter

**Comment by gkamer8** [comment] 2024-12-20 00:53
Cool - some information that might help: audio is delivered through a websocket from the backend to the browser, and it gets created like, 

```
const newSocket = io(process.env.NEXT_PUBLIC_BACKEND_URL + '/speak');
```

Your nginx proxy would have to be correctly configured to pass along websocket traffic and to do so to the correct path (/speak). FYI the hosted abbey backend runs at `https://abbeybackend.us.ai` so maybe issues around paths and websockets don't come up.

Next, just to make sure you're TTS setup is correct, I'll just give an example configuration for an openai_compatible setup:

```
openai_compatible:
  url: "https://api.openai.com" # Notice that I'm using the base URL, so not including /v1/audio/speech (which will get appended to it)
  
tts:
  default: "onyx-tts-1-openai_compatible"  # code names for TTS models are voice-model-provider, remember the underscore on openai_compatible
  voices:
    - provider: openai_compatible
      voice: fable
      model: tts-1  # make sure to include a model - the other one OpenAI supports is tts-1-hd
    - provider: openai_compatible
      voice: onyx
      model: tts-1
```

**Comment by gkamer8** [comment] 2024-12-20 02:23
Hey just FYI TTS for chat is now available in the dev branch! It'll show up next to the copy button. Still want to test more before merging.

**Comment by gkamer8** [comment] 2024-12-20 02:36
Also–

**Comment by gkamer8** [comment] 2024-12-20 02:38
**Also– I made a change in the dev branch to specify the path for the socket, which I think should help you keep using the /backend path scheme.** If you switch to that branch, you can see if it helps!

Your nginx proxy would still have to be correctly configured to handle connection upgrades (since the http connection is being upgraded to ws) - an example config might look like (according to gpt):
```
location /backend/ {
    proxy_pass http://your_flask_backend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by j0nathanr** [comment] 2024-12-20 03:37
Awesome, I'll try the dev branch out. Do I need to configure anything differently or will it just use the backend url specified in settings.yml for the socket path?

Also, when starting the dev compose file to test further, the frontend is failing to start:

```
> frontend@0.1.0 start
> next start

Error: ENOENT: no such file or directory, open '/frontend-build/.next/BUILD_ID'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async setupFsCheck (/frontend-build/node_modules/next/dist/server/lib/router-utils/filesystem.js:142:19)
    at async initialize (/frontend-build/node_modules/next/dist/server/lib/router-server.js:56:23)
    at async Server.<anonymous> (/frontend-build/node_modules/next/dist/server/lib/start-server.js:221:36) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/frontend-build/.next/BUILD_ID'
}
```

Looks like this is only an issue after building the production containers

**Comment by gkamer8** [comment] 2024-12-20 03:43
Ideally no extra configuration needed! I can't exactly reproduce your setup, but it now will specify the path for the socket as /backend/socket.io if you're using https:abbey.domain.domain/backend as your public backend URL.

For the frontend failing to start – you would see that issue if you switched to docker-compose.prod.yml without using --build. Let me know if you're using --build and it's still failing.

**Comment by j0nathanr** [comment] 2024-12-20 04:07
Got it, using docker compose up --build worked. I've gotten rid of the reverse proxy for now and am just using http, still with the main branch and I've confirmed the backend is reachable. Looks like the TTS server I'm using may not be fully compatible. I'm using [openedai](https://github.com/matatonic/openedai-speech), here's the backend log when trying to use TTS:

```
2024-12-20 03:51:30,465] ERROR in app: Exception on /user/tts-model [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/app/app/auth.py", line 61, in decorator
    return f(current_user, *args, **kwargs)
  File "/app/app/user.py", line 300, in get_user_tts_options_
    model: TTS = TTS_PROVIDERS[code]
KeyError: 'alloy'
/app/app/db.py:296: UserWarning: Tried to use existing connection for database, but RuntimeError occurred: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information..
  warnings.warn(f"Tried to use existing connection for database, but RuntimeError occurred: {str(e)}.")
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 589, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 618, in _trigger_event
    return handler.trigger_event(event, *args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/namespace.py", line 25, in trigger_event
    return self.socketio._handle_event(handler, event, self.namespace,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 838, in _handle_event
    ret = handler(*args)
  File "/app/app/speak.py", line 224, in on_start_stream
    self.stream_audio_via_websocket(model_code, txt, asset_id, name, speed)
  File "/app/app/speak.py", line 160, in stream_audio_via_websocket
    model: TTS = TTS_PROVIDERS[model_code]
KeyError: 'alloy'
2024-12-20T03:53:48Z <Thread at 0x7450f28580e0: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7450f3591c70>>(<socketio.server.Server object at 0x7450f3591c70>, 'Udys2CwaY6_VYn9lAAAB', '-B8eeiqOESB_vlGoAAAA', ['start_stream', {'txt': 'Here is a summary of the, '/speak', None)> failed with KeyError

[2024-12-20 03:55:18,094] ERROR in app: Exception on /user/tts-model [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/app/app/auth.py", line 61, in decorator
    return f(current_user, *args, **kwargs)
  File "/app/app/user.py", line 300, in get_user_tts_options_
    model: TTS = TTS_PROVIDERS[code]
KeyError: 'alloy'
[2024-12-20 03:55:29,549] ERROR in app: Exception on /user/tts-model [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/app/app/auth.py", line 61, in decorator
    return f(current_user, *args, **kwargs)
  File "/app/app/user.py", line 300, in get_user_tts_options_
    model: TTS = TTS_PROVIDERS[code]
KeyError: 'alloy'
```

Browser dev console logs:

```
       GET http://generator.lan:5000/user/tts-model 500 (INTERNAL SERVER ERROR)
getUserSelectedModel @ TTSModels.js:44
await in getUserSelectedModel
eval @ TTSModels.js:92
commitHookEffectListMount @ react-dom.development.js:23145
commitPassiveMountOnFiber @ react-dom.development.js:24921
commitPassiveMountEffects_complete @ react-dom.development.js:24886
commitPassiveMountEffects_begin @ react-dom.development.js:24873
commitPassiveMountEffects @ react-dom.development.js:24861
flushPassiveEffectsImpl @ react-dom.development.js:27034
flushPassiveEffects @ react-dom.development.js:26979
eval @ react-dom.development.js:26764
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 11 more frames
Show less
TTSModels.js:59 SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.
Error with Permissions-Policy header: Unrecognized feature: 'browsing-topics'.
6:1 

```

**Comment by j0nathanr** [comment] 2024-12-20 04:15
My settings.yml for reference:

```
tts:
  default: "alloy"
  voices:
    - provider: openai_compatible  # required
      voice: "alloy"  # required
      model: "tts-1-hd"  # required

openai_compatible:
  url: "http://openedai-speech-server-1:8000/v1"
```

.env
`
OPENAI_COMPATIBLE_KEY="1111"
`

**Comment by gkamer8** [comment] 2024-12-20 04:19
Hi– I see two problems that seem to be causing it:
1. The default isn't specified quite right. That's OK, just remove that line and it will default to the first voice (for reference, it should read "voice-model-provider" like "alloy-tts-1-hd-openai_compatible")
2. Your openai compatible server should probably be listed without the /v1. Abbey will automatically add /v1/audio/speech to the URL you give.

Let me know if any issues still persist!

**Comment by j0nathanr** [comment] 2024-12-20 04:26
Nice, both those modifications fixed the issue, TTS is working! Going to switch over to the dev branch to test it behind the reverse proxy, I'll report back

**Comment by j0nathanr** [comment] 2024-12-20 05:55
Workin perfectly behind the proxy now. The TTS feature under the chat messages also seems to be working without issue. Thanks for all the help!

**Comment by gkamer8** [comment] 2024-12-20 07:22
Awesome, glad you were able to get everything working!

**Closed as completed** 2024-12-20 07:23 UTC
